CREATE TABLE PHONES (
	PHONE_PK INT NOT NULL DEFAULT NEXTVAL('phone_pk_seq') PRIMARY KEY,
	PHONE_ID VARCHAR(10) NOT NULL UNIQUE,
	NAME VARCHAR(50) NOT NULL,
	OPINION VARCHAR(300),
	PRICE NUMERIC(8,2) NOT NULL CHECK (PRICE > 0)
);

-- INSERT INTO PHONES (PHONE_ID, NAME, OPINION, PRICE) VALUES ('111', 'Motorola ABC', 'Good, as for Motorola', 450.00);
-- INSERT INTO PHONES (PHONE_ID, NAME, OPINION, PRICE) VALUES ('236', 'Motorola 543', 'Not Bad', 300.50);
-- INSERT INTO PHONES (PHONE_ID, NAME, OPINION, PRICE) VALUES ('789', 'Dell XYZ', 'Best of all DELLs', 510.40);
-- INSERT INTO PHONES (PHONE_ID, NAME, OPINION, PRICE) VALUES ('234', 'Samsung S3', 'Simply, the best', 720.31);